name: jobtrail

services:
    migrations:
        image: ghcr.io/matfire/jobtrail-migrations
        container_name: jobtrail-migrations
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432/jobtrail}
        restart: on-failure

    server:
        image: ghcr.io/matfire/jobtrail-server
        container_name: jobtrail-server
        depends_on:
            postgres:
                condition: service_healthy
            migrations:
                condition: service_completed_successfully
        environment:
            DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432/jobtrail}
            BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-change-me-in-production}
            BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
            CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3001}
            PORT: 3000
        ports:
            - "3000:3000"
        restart: unless-stopped

volumes:
    jobtrail_postgres_production_data:
