packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.10.0
  '@orpc/openapi': ^1.10.0
  '@orpc/server': ^1.10.0
  '@orpc/zod': ^1.10.0
  '@polar-sh/better-auth': ^1.1.3
  better-auth: ^1.4.0
  dotenv: ^17.2.2
  hono: ^4.8.2

onlyBuiltDependencies:
  - esbuild
