packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/zod': ^1.12.2
  better-auth: ^1.4.5
  dotenv: ^17.2.3
  hono: ^4.10.7

onlyBuiltDependencies:
  - esbuild
